title: Hello, world! I'm Gina Sarfaty.
description: > # this means to ignore newlines until "baseurl:"
  This is a space to share my work, and connect with others.
permalink: ':title/'
url: "https://gsarfaty.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Gina Sarfaty # add your name
author-img: gina-sarfaty.jpg # add your photo
about-author: I am a data analytics professional, seeking to continuously learn and grow. # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: gsarfaty # add your Github handle
social-linkedin: ginasarfaty # add your Linkedin handle
social-email: grumbolo@gmail.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
